"""empty message

Revision ID: 0000649576c4
Revises: 57a5beb00c83
Create Date: 2024-10-18 10:24:19.635110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0000649576c4'
down_revision = '57a5beb00c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosisEncounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=True),
    sa.Column('diagnosis_description', sa.String(length=255), nullable=True),
    sa.Column('tooth_number', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosisEncounters')
    # ### end Alembic commands ###
