"""empty message

Revision ID: 021442d7c040
Revises: 23b907a5a366
Create Date: 2024-09-03 14:39:40.044414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '021442d7c040'
down_revision = '23b907a5a366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.drop_column('post_instructions')
        batch_op.drop_column('prior_instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prior_instructions', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('post_instructions', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
