"""empty message

Revision ID: 050a71ae4441
Revises: 1a8f0ae6f1fe
Create Date: 2024-08-31 16:46:04.120757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '050a71ae4441'
down_revision = '1a8f0ae6f1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rootcanal', schema=None) as batch_op:
        batch_op.drop_column('root_canal_middle')
        batch_op.drop_column('root_canal_right')
        batch_op.drop_column('root_canal_left')
        batch_op.drop_column('root_canal_lower')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rootcanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_canal_lower', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('root_canal_left', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('root_canal_right', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('root_canal_middle', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
