"""add to booking encounter

Revision ID: 09d05b7aefb4
Revises: b4fef4a2ded2
Create Date: 2025-01-12 21:18:37.311293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d05b7aefb4'
down_revision = 'b4fef4a2ded2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_sent')

    # ### end Alembic commands ###
