"""add column in user table

Revision ID: 19200f2a6477
Revises: 542eff6129aa
Create Date: 2025-01-08 16:14:23.658047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19200f2a6477'
down_revision = '542eff6129aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinics_number', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clinics_number')

    # ### end Alembic commands ###
