"""changes

Revision ID: 1a0594889e24
Revises: 96f72c1141c9
Create Date: 2024-09-30 11:26:56.910858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0594889e24'
down_revision = '96f72c1141c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_one_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reminder_two_date', sa.Date(), nullable=True))
        batch_op.drop_column('reminder_sending_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sending_date', sa.DATE(), nullable=True))
        batch_op.drop_column('reminder_two_date')
        batch_op.drop_column('reminder_one_date')

    # ### end Alembic commands ###
