"""empty message

Revision ID: 1a8f0ae6f1fe
Revises: 88659344a911
Create Date: 2024-08-30 16:56:33.106605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a8f0ae6f1fe'
down_revision = '88659344a911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_bill', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('current_patients', sa.Boolean(), nullable=True))
        batch_op.drop_column('bill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('current_patients')
        batch_op.drop_column('old_bill')

    # ### end Alembic commands ###
