"""empty message

Revision ID: 2c9040c97021
Revises: 3263623dbea2
Create Date: 2024-09-18 23:11:04.971894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c9040c97021'
down_revision = '3263623dbea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientInfo', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('allergy_reaction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergy_reaction', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
