"""empty message

Revision ID: 3263623dbea2
Revises: 021442d7c040
Create Date: 2024-09-03 14:57:09.591505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3263623dbea2'
down_revision = '021442d7c040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.drop_column('appointment_reminder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_reminder', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
