"""empty message

Revision ID: 3932863045b1
Revises: d1e8d3c1610d
Create Date: 2025-01-18 20:46:01.906452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3932863045b1'
down_revision = 'd1e8d3c1610d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientInfo', schema=None) as batch_op:
        batch_op.drop_column('patient_image')

    # ### end Alembic commands ###
