"""empty message

Revision ID: 48d52d01e3ac
Revises: 5a67041763c0
Create Date: 2024-11-03 14:35:09.682236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d52d01e3ac'
down_revision = '5a67041763c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_column('diagnosis')

    # ### end Alembic commands ###
