"""empty message

Revision ID: 51d4020760b2
Revises: f079f27003a9
Create Date: 2024-09-29 16:45:41.137553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d4020760b2'
down_revision = 'f079f27003a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patientId', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.drop_column('patientId')

    # ### end Alembic commands ###
