"""empty message

Revision ID: 542eff6129aa
Revises: 48d52d01e3ac
Create Date: 2024-11-09 16:22:28.427650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542eff6129aa'
down_revision = '48d52d01e3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosisCopy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('diagnosis_description', sa.String(length=255), nullable=True),
    sa.Column('tooth_number', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosisCopy')
    # ### end Alembic commands ###
