"""changes

Revision ID: 57a5beb00c83
Revises: 7c5cf802594d
Create Date: 2024-10-04 10:10:43.874216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a5beb00c83'
down_revision = '7c5cf802594d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crown_surface', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crowns')
    # ### end Alembic commands ###
