"""empty message

Revision ID: 5a67041763c0
Revises: e32feca0674b
Create Date: 2024-11-01 09:33:09.705171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a67041763c0'
down_revision = 'e32feca0674b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_column('procedureIcon')
        batch_op.drop_column('procedureCategory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedureCategory', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('procedureIcon', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
