"""add new table

Revision ID: 5cdf6c86d6e7
Revises: 2c9040c97021
Create Date: 2024-09-24 15:26:44.943561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdf6c86d6e7'
down_revision = '2c9040c97021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patientInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_documents')
    # ### end Alembic commands ###
