"""changes

Revision ID: 647ea2d70e04
Revises: 09d05b7aefb4
Create Date: 2025-01-13 23:30:49.928868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647ea2d70e04'
down_revision = '09d05b7aefb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wa_phone_number_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('waba_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('business_code')
        batch_op.drop_column('token_code')
        batch_op.drop_column('waba_id')
        batch_op.drop_column('wa_phone_number_id')

    # ### end Alembic commands ###
