"""empty message

Revision ID: 664e1496d614
Revises: 0000649576c4
Create Date: 2024-10-18 10:52:49.518077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664e1496d614'
down_revision = '0000649576c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosisEncounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('clinic_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosisEncounters', schema=None) as batch_op:
        batch_op.drop_column('clinic_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
