"""changes

Revision ID: 7c5cf802594d
Revises: d748264c2b5f
Create Date: 2024-10-02 23:06:56.006600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5cf802594d'
down_revision = 'd748264c2b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosisDescription', sa.String(length=255), nullable=True),
    sa.Column('diagnosisCategory', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosis')
    # ### end Alembic commands ###
