"""empty message

Revision ID: 80794d764ec4
Revises: e384a3498ef5
Create Date: 2024-10-30 11:36:42.698624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80794d764ec4'
down_revision = 'e384a3498ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatmentencounter', schema=None) as batch_op:
        batch_op.drop_column('diagnosis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatmentencounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
