"""changes

Revision ID: 91808f4eb8d9
Revises: 5cdf6c86d6e7
Create Date: 2024-09-27 17:58:08.913756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91808f4eb8d9'
down_revision = '5cdf6c86d6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_column('clinic_name')

    # ### end Alembic commands ###
