"""changes

Revision ID: 96f72c1141c9
Revises: 73ed1f4592b4
Create Date: 2024-09-30 11:00:27.117344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96f72c1141c9'
down_revision = '73ed1f4592b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.alter_column('reminder_sending_date',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.alter_column('reminder_sending_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
