"""changes

Revision ID: b4fef4a2ded2
Revises: 19200f2a6477
Create Date: 2025-01-09 07:48:57.594259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4fef4a2ded2'
down_revision = '19200f2a6477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clinics_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinics_number', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
