"""empty message

Revision ID: d1bfe188e31c
Revises: 1a0594889e24
Create Date: 2024-10-01 14:47:50.669337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bfe188e31c'
down_revision = '1a0594889e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivate_reminder', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders_sent', schema=None) as batch_op:
        batch_op.drop_column('deactivate_reminder')

    # ### end Alembic commands ###
