"""empty message

Revision ID: d1e8d3c1610d
Revises: 18804257ea27
Create Date: 2025-01-16 13:10:04.695609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1e8d3c1610d'
down_revision = '18804257ea27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_booking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_appointment', sa.Boolean(), nullable=True))
        batch_op.drop_column('whatsapp_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookingEncounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('whatsapp_appointment')
        batch_op.drop_column('whatsapp_booking')

    # ### end Alembic commands ###
