"""changes

Revision ID: d748264c2b5f
Revises: d1bfe188e31c
Create Date: 2024-10-02 10:24:48.881212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd748264c2b5f'
down_revision = 'd1bfe188e31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rootcanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composite_circle', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rootcanal', schema=None) as batch_op:
        batch_op.drop_column('composite_circle')

    # ### end Alembic commands ###
