"""empty message

Revision ID: dd21d2b29355
Revises: 647ea2d70e04
Create Date: 2025-01-14 22:08:54.804248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd21d2b29355'
down_revision = '647ea2d70e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_facebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('wa_phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('waba_id', sa.String(length=255), nullable=True),
    sa.Column('token_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wa_phone_number_id')
        batch_op.drop_column('token_code')
        batch_op.drop_column('business_code')
        batch_op.drop_column('waba_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('wa_phone_number_id', mysql.VARCHAR(length=255), nullable=True))

    op.drop_table('user_facebook')
    # ### end Alembic commands ###
