"""empty message

Revision ID: e32feca0674b
Revises: eedbb2919c5c
Create Date: 2024-10-31 13:29:32.115703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e32feca0674b'
down_revision = 'eedbb2919c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_column('diagnosisCategory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosisCategory', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
