"""adjust pricing table

Revision ID: e384a3498ef5
Revises: 123950ed3edc
Create Date: 2024-10-22 20:27:17.313308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e384a3498ef5'
down_revision = '123950ed3edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
