"""empty message

Revision ID: ea207ec64a17
Revises: dd21d2b29355
Create Date: 2025-01-14 22:10:40.641996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea207ec64a17'
down_revision = 'dd21d2b29355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userFacebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('wa_phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('waba_id', sa.String(length=255), nullable=True),
    sa.Column('token_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_facebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_facebook',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('clinic_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('wa_phone_number_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('waba_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('token_code', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('userFacebook')
    # ### end Alembic commands ###
